/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.retail;

import generated.grpc.InventoryRefill.InventoryRestockGrpc;
import generated.grpc.InventoryRefill.RestockRequest;
import generated.grpc.InventoryRefill.RestockSummary;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;
import java.util.Random;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class InventoryRefillGUI extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(InventoryRefillGUI.class.getName());
    // a non blocking stub to make asynchronous call
    private static InventoryRestockGrpc.InventoryRestockStub asyncStub;
    private DefaultTableModel table;
    ManagedChannel channel;
    StreamObserver<RestockRequest> requestObserver;
    Random random = new Random();
       

    /**
     * Creates new form InventoryRefillGUI
     */
    public InventoryRefillGUI() {
        initComponents();
        // initializing the table and cleaning any data 
        table = (DefaultTableModel) inventoryTable.getModel();
        table.setRowCount(0);

        channel = ManagedChannelBuilder
                .forAddress("localhost", 50051)
                .usePlaintext()
                .build();
        asyncStub = InventoryRestockGrpc.newStub(channel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        submitBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputRestock = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product ID", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(inventoryTable);

        submitBtn.setText("Send Restock");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        output.setEditable(false);
        output.setColumns(20);
        output.setLineWrap(true);
        output.setRows(5);
        jScrollPane2.setViewportView(output);

        jLabel2.setText("Start inventory by clicking on the button bellow");

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        outputRestock.setEditable(false);
        outputRestock.setColumns(20);
        outputRestock.setLineWrap(true);
        outputRestock.setRows(5);
        jScrollPane3.setViewportView(outputRestock);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Products with low quantity in stock:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(start)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(submitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(start)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if (table.getRowCount() == 0) {
            outputRestock.setText("All products have a good quantity in the stock.");
            return;
        }

        outputRestock.setText("Sending requests.\n");

        StreamObserver<RestockSummary> responseObserver = new StreamObserver<RestockSummary>() {
            @Override
            public void onNext(RestockSummary summary) {
                outputRestock.append("Information about the restock submission:\n");
                outputRestock.append("Total processed: " + summary.getTotalProcessed() + "\n");
                outputRestock.append("Total Failed: " + summary.getTotalFailed() + "\n");
            }

            @Override
            public void onError(Throwable t) {
                outputRestock.append("Error: " + t.getMessage() + "\n");
            }

            @Override
            public void onCompleted() {
                outputRestock.append("Stream completed.\n");
            }
        };

        // sending tables data 
        StreamObserver<RestockRequest> requestObserver = asyncStub.bulkRestock(responseObserver);

        //loop to take productID and quantities and send it to the server
        for (int i = 0; i < table.getRowCount(); i++) {
            String id = table.getValueAt(i, 0).toString();
            int qty = (Integer) table.getValueAt(i, 1);

            RestockRequest request = RestockRequest.newBuilder()
                    .setProductId(id)
                    .setQuantity(qty)
                    .build();

            requestObserver.onNext(request);
            output.append("Sending request for Product ID: " + id + ", Quantity: " + qty + "\n");

        }

        requestObserver.onCompleted();
        
        // Clear the table
        table.setRowCount(0);

        // Show confirmation message in the text area
        output.append("Request sent successfully!");


    }//GEN-LAST:event_submitBtnActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        output.setText("");
        output.append("Initializing inventory:\n");
        
        for (int i = 0; i < 100; i++) {
            String id = randomProductID();  
            int qty = randomQuantity();   

            output.append("Product ID: " + id + ", quantity: " + qty + "\n");
            
            if(qty < 10) {
            // Adding to the list to be restocked
            outputRestock.append("Product ID: " + id + " added to the list.\n");

            table.addRow(new Object[]{id, qty});
            }
        }
    }//GEN-LAST:event_startActionPerformed
    
    //recursive method to generate a random ID for productID(){
    private String randomProductID(){
        int id = random.nextInt(1000); 
        return String.format("R%03d", id);
    }
    
    //recursive method to generate a random quantity for the product
    private int randomQuantity(){
        return random.nextInt(100) + 1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, UnsupportedLookAndFeelException, IllegalAccessException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryRefillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryRefillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryRefillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryRefillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryRefillGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inventoryTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea output;
    private javax.swing.JTextArea outputRestock;
    private javax.swing.JButton start;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
